### ISSUE TITLE
115 kilobyte MIDI lump

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/test-wads#4]
Finally, found a suitable MIDI file with >96 kilobyte size: [115KMIDI.zip](https://github.com/fabiangreffrath/test-wads/files/7062788/115KMIDI.zip) (replaces `D_RUNNIN`, music of Doom II first map).
It's from Sunder MAP32. But I can't find it's author and license, so can we still publish it?

**Comment by JNechaevsky** [comment]
Ah, here it is, hidden in depth of readme file:
> Music by Eris for Panophobia titled "Aorta"

Published here: https://www.doomworld.com/forum/topic/111911-the-eris-midi-thread/. Guess we are fine.

**Comment by fabiangreffrath** [comment]
Well, "Feel free to use any of these﻿, providing credit is given﻿" isn't exactly the same as CC0-1.0. I'll have to ask him on DW.

**Comment by fabiangreffrath** [comment]
I sent him a PM.
